version: '3.8'
services:
    fastapi-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        environment:
            REDIS_URL: "redis://username:password@redis:6379/0"
            USERNAME: your-username
            PASSWORD: your-password
        depends_on:
            - redis

    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        command: redis-server --requirepass your-password
